### ISSUE TITLE
Export .osim and .mot files after align to SMPL

### ISSUE THREAD

**Issue by yinyunie** [MarilynKeller/SKEL#2]
Hi Marilyn,

Thanks a lot for your contributions in connecting SMPL with Biometric skeletons. I really like your code pool. It is very clear and compact.

May I ask if it is possible to export `*.osim` and `*.mot` files as well from the SMPL alignment script below, so that can connect with many applications on opensim?
```
python examples/align_to_SMPL.py /path/to/AMASS/CMU/01/01_01_poses.npz -F  
```

Thanks a lot.

Best,
Yinyu

**Comment by MarilynKeller** [comment]
Hi Yinye,

The export will not be possible from SKEL, but I am working on releasing the last piece of code that allows to fit bsm.osim directly to a SMPL sequence. I should be out in a couple of days on my github.

Best,
Marilyn

**Comment by yinyunie** [comment]
Thanks Marily! That will be quite helpful. 

I was trying to write the export function myself since I found the DoFs of the BSM model are the same as in SKEL. However, I found it not easy, since nimble is using the y-up coordinate system while SMPL and SKEL are z-up, and the rotation axis for each DoF is also hard to align.

**Comment by MarilynKeller** [comment]
Indeed that might be tricky for several reason:
- Although the degrees of freedom are the same, the rest pose is not the same so that is blocking at the moment. I.e. if you set the pose parameter q to all zeros in SKEL you will get a T pose, while with BSM you'll get a "I" pose.
- The implementation of the spine and the scapula are slightly different for now so the same pose parameters could lead to slightly different poses.

Again, I am going to release the code to directly fit an OpenSim model sequence to a SMPL sequence. That might meet your needs better. I'll announce as soon as it is out.

**Comment by yinyunie** [comment]
Thanks a lot for your information, it really helps to understand the design, and thanks again for the coming update.

**Comment by MarilynKeller** [comment]
Hi there, I released the code to given  a SMPL sequence, lets you fit a .osim model to it to get a scaled .osim model and the corresponding .mot. 
The repo is here: https://github.com/MarilynKeller/SMPL2AddBiomechanics
I hope it will meet your need !

**Comment by yinyunie** [comment]
Thanks Marilyn, Really really appreciate it!
